version: '3.3'
services:
  master:
    image: amertz08/spark
    environment:
      - LOG_FILE=spark-master-log.out
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    command: runner master

  worker:
    image: amertz08/spark
    environment:
      - LOG_FILE=spark-worker-log.out
    ports:
      - "8081"
      - "5000"
    command: runner worker master

  notebook:
    build: amertz08/spark-jupyter
    ports:
      - "8888:8888"

    command: runner py master
