version: '3.3'
services:
  master:
    image: amertz08/spark
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    volumes:
      - logs:/var/log/spark
    command: runner master

  worker:
    image: amertz08/spark
    ports:
      - "8081"
      - "5000"
    command: runner worker master

  notebook:
    image: amertz08/spark-jupyter
    ports:
      - "8888:8888"
    command: runner py master
    volumes:
        - notebooks:/home/notebook/code

volumes:
  notebooks:
  logs:
